// Code generated by mockery v2.53.2. DO NOT EDIT.

package mock_nodes

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/horockey/service_discovery/internal/model"
)

// MockReadOnlyRepo is an autogenerated mock type for the ReadOnlyRepo type
type MockReadOnlyRepo struct {
	mock.Mock
}

type MockReadOnlyRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadOnlyRepo) EXPECT() *MockReadOnlyRepo_Expecter {
	return &MockReadOnlyRepo_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockReadOnlyRepo) GetAll(ctx context.Context) ([]model.Node, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Node
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Node, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Node); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Node)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReadOnlyRepo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockReadOnlyRepo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReadOnlyRepo_Expecter) GetAll(ctx interface{}) *MockReadOnlyRepo_GetAll_Call {
	return &MockReadOnlyRepo_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockReadOnlyRepo_GetAll_Call) Run(run func(ctx context.Context)) *MockReadOnlyRepo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReadOnlyRepo_GetAll_Call) Return(_a0 []model.Node, _a1 error) *MockReadOnlyRepo_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReadOnlyRepo_GetAll_Call) RunAndReturn(run func(context.Context) ([]model.Node, error)) *MockReadOnlyRepo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadOnlyRepo creates a new instance of MockReadOnlyRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadOnlyRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadOnlyRepo {
	mock := &MockReadOnlyRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
